name: Node CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Lint, Test, and Build
        run: |
          yarn install --frozen-lockfile
          yarn lint
          yarn test
          yarn build
        env:
          CI: true
